export class Pdftemplet {
    /**
     *
     * @param {string} title
     * @param {string} subTitle
     * @param {string} generatedBy
     * @param {string} reportId
     * @param {string[]} headers
     * @param {string[]} body
     */
    constructor(title, subTitle, generatedBy, reportId, headers, body) {
        this.title = title;
        this.subTitle = subTitle;
        this.generatedBy = generatedBy;
        this.reportId = reportId;
        this.headers = headers;
        this.body = body;
    }

    // Method to display report information
    displayReportInfo() {
        console.log(`Title: ${this.title}`);
        console.log(`Subtitle: ${this.subTitle}`);
        console.log(`Generated By: ${this.generatedBy}`);
        console.log(`Report ID: ${this.reportId}`);
    }

    // Method to display report headers
    displayHeaders() {
        console.log(this.headers.join(' | '));
    }

    // Method to display report body
    displayBody() {
        this.body.forEach((row) => {
            console.log(row.join(' | '));
        });
    }

    // Method to display full report
    displayFullReport() {
        this.displayReportInfo();
        console.log('\nHeaders:');
        this.displayHeaders();
        console.log('\nBody:');
        this.displayBody();
    }
}
