name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch where you develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project (if needed)
        run: npm run build # Replace with your build script, if applicable

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
